import os
import time

# --- STUB FLAG ---
# Set to False to try loading real models (requires heavy dependencies & best_model.pth)
USE_STUBS = True

def load_models():
    """Loads all AI models into memory."""
    if USE_STUBS:
        print("Loading MOCK models...")
        return {"status": "Mock models loaded"}
    
    print("Loading REAL models...")
    import whisper
    from sentence_transformers import SentenceTransformer
    from keybert import KeyBERT
    import torch
    import torch.nn as nn
    
    # Custom BiLSTM + Attention Model Definition
    class BiLSTMAttention(nn.Module):
        def __init__(self, embedding_dim, hidden_dim, output_dim):
            super().__init__()
            self.lstm = nn.LSTM(embedding_dim, hidden_dim, bidirectional=True, batch_first=True)
            self.attention = nn.Linear(hidden_dim * 2, 1)
            self.fc = nn.Linear(hidden_dim * 2, output_dim)
            
        def forward(self, x):
            lstm_out, _ = self.lstm(x)
            attn_weights = torch.softmax(self.attention(lstm_out), dim=1)
            attn_applied = torch.sum(attn_weights * lstm_out, dim=1)
            output = self.fc(attn_applied)
            return output

    # Load Whisper
    whisper_model = whisper.load_model("base")
    
    # Load Sentence-BERT
    sbert_model = SentenceTransformer('all-MiniLM-L6-v2')
    
    # Load KeyBERT
    keybert_model = KeyBERT()
    
    # Load Custom BiLSTM Model (Requires best_model.pth)
    model_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'models', 'best_model.pth')
    bilstm_model = None
    if os.path.exists(model_path):
        bilstm_model = BiLSTMAttention(embedding_dim=384, hidden_dim=128, output_dim=1)
        bilstm_model.load_state_dict(torch.load(model_path, map_location=torch.device('cpu')))
        bilstm_model.eval()
    else:
        print(f"Warning: Custom model not found at {model_path}. Summarization may fail if stubs are off.")
        
    return {
        "whisper": whisper_model,
        "sbert": sbert_model,
        "keybert": keybert_model,
        "bilstm": bilstm_model
    }

models_cache = None

def get_models():
    global models_cache
    if models_cache is None:
        models_cache = load_models()
    return models_cache

def process_audio(file_path: str):
    """
    Main pipeline:
    1. Whisper transcription
    2. Text cleaning
    3. Topic extraction using KeyBERT
    4. Sentence embeddings using S-BERT
    5. Summarization using BiLSTM
    """
    models = get_models()
    
    if USE_STUBS:
        # Simulate processing time
        time.sleep(3)
        return {
            "transcript": "This is a simulated transcript from the uploaded audio file. In a real scenario, this would be generated by the Whisper base model. We are discussing Artificial Intelligence today, specifically Deep Learning and how neural networks can learn patterns in complex data.",
            "formatted_notes": "# Artificial Intelligence\n\n- AI simulates human intelligence\n- Machine learning is subset of AI\n\n# Deep Learning\n\n- Neural networks learn patterns\n- LSTM handles sequence data\n\n# Summary\n\n- Simulated output from the custom BiLSTM + Attention model.",
            "topics": ["Artificial Intelligence", "Deep Learning", "Neural Networks", "LSTM", "Machine Learning"]
        }
    
    # --- REAL INFERENCE LOGIC ---
    print(f"Processing audio with real models: {file_path}")
    
    # 1. Transcription
    whisper_model = models["whisper"]
    result = whisper_model.transcribe(file_path)
    transcript = result["text"]
    
    # 2. Text Cleaning (Basic)
    cleaned_text = transcript.strip().replace("  ", " ")
    
    # 3. Topic Extraction
    keybert_model = models["keybert"]
    keywords = keybert_model.extract_keywords(cleaned_text, keyphrase_ngram_range=(1, 2), stop_words='english', top_n=5)
    topics = [kw[0] for kw in keywords]
    
    # 4 & 5. Summarization (Sentence-BERT + BiLSTM)
    sbert_model = models["sbert"]
    bilstm_model = models["bilstm"]
    
    formatted_notes = ""
    
    if bilstm_model is not None:
        import nltk
        try:
            nltk.data.find('tokenizers/punkt')
        except LookupError:
            nltk.download('punkt')
        from nltk.tokenize import sent_tokenize
        import torch

        sentences = sent_tokenize(cleaned_text)
        embeddings = sbert_model.encode(sentences)
        
        # Inference using BiLSTM to score sentences
        tensor_embeddings = torch.tensor(embeddings).unsqueeze(1) # Add batch/sequence dim appropriately depending on actual model expectation
        with torch.no_grad():
            scores = bilstm_model(tensor_embeddings)
        
        # Select top N sentences based on scores
        # (This is a simplified assumption of how the BiLSTM is used. Actual logic depends on the specific model architecture)
        scored_sentences = zip(sentences, scores.squeeze().tolist())
        top_sentences = sorted(scored_sentences, key=lambda x: x[1], reverse=True)[:max(3, len(sentences)//3)]
        
        formatted_notes += "# Smart Summary\n\n"
        for sent, score in top_sentences:
            formatted_notes += f"- {sent}\n"
    else:
        formatted_notes = "# Notes\n\n(Custom BiLSTM model weights not found. Returning raw transcript preview)\n\n" + cleaned_text[:500] + "..."

    return {
        "transcript": transcript,
        "formatted_notes": formatted_notes,
        "topics": topics
    }
